apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: file
  name: file
spec:
  ports:
    - name: "3000"
      port: 80
      targetPort: 3000
  selector:
    io.kompose.service: file
  type: LoadBalancer
status:
  loadBalancer: {}
